version: "3.8"

services:
  api:
    build: ./api
    container_name: api
    ports:
      - 4000:4000
    volumes:
      - ./api:/app
  react-docker:
    container_name: react-docker
    image: react-docker
    build: ./react-docker
    ports:
      - 3000:3000
    volumes:
      - ./react-docker/src:/app/src

